# AkaiGrid Config File
# Remove the '#' at the beginning of the lines to set the values

##### Since 1.0.0

# Your Video Folders (Full Path only)
# It supports Windows paths like "C:\Videos" and network paths like "\\MY_SMB\Videos"
# The order of the folders will be the same as the order in the list.
# Btw, this config file is in YAML format, so be careful with indentation!
folders:
    - C:\MyExampleVideosFolder
    - C:\MyExampleMoviesFolder

# After opened a video or set a video to be done, modify its folder's last access date to now.
# So that the folder will be in the top of the list, it will be more convenient to find the series next time if the folder is sorted by "Date Accessed / Desc".
# (true or false) (default: false)
#bringFolderToTop: false

# Right click a item to set it as done and also bring its folder to the top of the list.
# (true or false) (default: false)
#bringFolderToTopDone: false

# Launch browser automatically?
# (true or false) (default: true)
#launchBrowser: true

# Hide dotfiles? (true or false) (default: true)
#hideDotfiles: true

# Listening Port
# (number) (default: 60001)
#port: 60001

# Host
# ⚠️ Expose it to the internet is dangerous! ⚠️ Don't touch this unless you know what you're doing!
# (string) (default: 127.0.0.1)
#host: 127.0.0.1

##### Since 1.0.2

# Update Date accessed to now when the video is opened?
# So that the video file will be in the top of the list, it will be more convenient to find the video if the folder is sorted by "Date Accessed / Desc".
# (true or false) (default: false)
updateDateAccessed: false
