# Run it via `deno task demo-container` in the project root
# The working directory is set to the root of the project

services:
    app:
        build:
            context: .
            dockerfile: ./extra/demo/Dockerfile
        ports:
            - "60001:60001"
        environment:
            - NODE_ENV=demo
        restart: unless-stopped
    cloudflared:
        image: cloudflare/cloudflared:latest
        command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
        restart: unless-stopped
