name: Test Setup

# Manual trigger
on:
    workflow_dispatch:

jobs:
    deno-test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest]
                deno: [v2.x]

        steps:
            - name: Turn off core.autocrlf
              run: git config --global core.autocrlf false

            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: ${{ matrix.deno }}

            - name: Production Test (Setup)
              run: deno task setup

            - name: Dev Test (setup:dev)
              run: deno task setup:dev
