name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]


jobs:
  deno-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: stable

      - name: Check
        run: deno task check

      - name: Test
        run: deno task test

